apiVersion: v1
kind: Service
metadata:
  name: hmcts-complaints-formbuilder-adapter
  labels:
    app: hmcts-complaints-formbuilder-adapter
spec:
  ports:
  - port: 3000
    name: http
    targetPort: 3000
  selector:
    app: hmcts-complaints-formbuilder-adapter
