version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - brenetic
  - tomas-stefano
  - mattempty
  - njseeto
  ignore:
  - dependency-name: sentry-raven
    versions:
    - 3.1.1
  - dependency-name: delayed_job_active_record
    versions:
    - 4.1.5
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
    - 4.1.1
    - 5.0.0
  - dependency-name: rubocop
    versions:
    - 1.9.0
- package-ecosystem: docker
  directory: "/docker/api"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - brenetic
  - tomas-stefano
  - mattempty
  - njseeto
  ignore:
  - dependency-name: ruby
    versions:
    - 3.0.0.pre.alpine3.12
    - 3.0.1.pre.alpine3.12
- package-ecosystem: docker
  directory: "/docker/worker"
  schedule:
    interval: daily
    time: "03:00"
    timezone: Europe/London
  open-pull-requests-limit: 10
  reviewers:
  - brenetic
  - tomas-stefano
  - mattempty
  - njseeto
  ignore:
  - dependency-name: ruby
    versions:
    - 3.0.0.pre.alpine3.12
    - 3.0.1.pre.alpine3.12
