AllCops:
  Exclude:
  - '.bundle/**'
  - 'bin/**'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  Max: 40

Metrics/MethodLength:
  Max: 15
