require: rubocop-rspec

AllCops:
  Exclude:
  - .bundle/**
  - bin/**
  - db/schema.rb
  - Guardfile

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - db/**/*
