require: rubocop-rspec

AllCops:
  Exclude:
  - '.bundle/**'
  - 'bin/**'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe']

