require: rubocop-rspec

AllCops:
  Exclude:
  - '.bundle/**'
  - 'bin/**'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - db/schema.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - db/schema.rb

Style/PercentLiteralDelimiters:
  Exclude:
    - Guardfile

Style/StringLiterals:
  Exclude:
    - db/schema.rb
    - Guardfile

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Exclude:
    - db/schema.rb

Metrics/LineLength:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
  Exclude:
    - Guardfile

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - db/**/*
