require:
- rubocop-rspec
- rubocop-factory_bot

AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
  - .bundle/**
  - bin/**
  - db/schema.rb
  - Guardfile
  - config/environments/**
  - spec/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'let']

Metrics/MethodLength:
  Enabled: true
  Exclude:
    - db/**/*

RSpec/MultipleMemoizedHelpers:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/VariableNumber:
  Enabled: false
