version: '3.4'

services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: hmcts_complaints_form_builder_adapter
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DATABASE_URL: "postgres://postgres:password@db/hmcts_complaints_form_builder_adapter"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
