version: '3.4'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: hmcts_complaints_form_builder_adapter
  app:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
      args:
        UID: "${UID}"
        RAILS_ENV: "test"
        BUNDLE_FLAGS: '--jobs 2 --no-cache'
    user: "${UID}:${UID}"
    environment:
      DATABASE_URL: "postgres://postgres:password@db/hmcts_complaints_form_builder_adapter"
      SENTRY_DSN: ''
    ports:
      - "3000:3000"
    depends_on:
      - db
