apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hmcts-complaints-formbuilder-adapter
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hmcts-complaints-formbuilder-adapter
    spec:
      containers:
      - name: hmcts-complaints-formbuilder-adapter
        image: 754256621582.dkr.ecr.eu-west-2.amazonaws.com/form-builder/hmcts-complaints-formbuilder-adapter:{{ .Values.imagetag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        env:
        - name: RAILS_LOG_TO_STDOUT
          value: "true"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: hmcts-complaints-formbuilder-adapter-secret
              key: SECRET_KEY_BASE
        - name: JWE_SHARED_KEY
          valueFrom:
            secretKeyRef:
              name: hmcts-complaints-formbuilder-adapter-secret
              key: JWE_SHARED_KEY
        - name: OPTICS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: hmcts-complaints-formbuilder-adapter-secret
              key: OPTICS_SECRET_KEY
        - name: OPTICS_API_KEY
          valueFrom:
            secretKeyRef:
              name: hmcts-complaints-formbuilder-adapter-secret
              key: OPTICS_API_KEY
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              name: hmcts-complaints-formbuilder-adapter-secret
              key: SENTRY_DSN
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: rds-instance-hmcts-complaints-adapter-{{ .Values.environmentName }}
              key: url
