apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hmcts-complaints-formbuilder-adapter-{{ .Values.environmentName }}
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "hmcts-complaints-formbuilder-adapter-{{ .Values.environmentName }}-hmcts-complaints-formbuilder-adapter-{{ .Values.environmentName }}-green"
    external-dns.alpha.kubernetes.io/aws-weight: "100"
spec:
  ingressClassName: default
  tls:
    - hosts:
        - hmcts-complaints-formbuilder-adapter-{{ .Values.environmentName }}.apps.live.cloud-platform.service.justice.gov.uk
  rules:
  - host: hmcts-complaints-formbuilder-adapter-{{ .Values.environmentName }}.apps.live.cloud-platform.service.justice.gov.uk
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: hmcts-complaints-formbuilder-adapter
            port:
              number: 3000
