apiVersion: v1
kind: Secret
metadata:
  name: hmcts-complaints-formbuilder-adapter-secrets-{{ .Values.environmentName }}
type: Opaque
data:
  jwe_shared_key: {{ .Values.jwe_shared_key }}
  metrics_auth_password: {{ .Values.metrics_auth_password }}
  metrics_auth_username: {{ .Values.metrics_auth_username }}
  optics_api_key: {{ .Values.optics_api_key }}
  optics_endpoint: {{ .Values.optics_endpoint }}
  optics_secret_key: {{ .Values.optics_secret_key }}
  secret_key_base: {{ .Values.secret_key_base }}
  sentry_dsn: {{ .Values.sentry_dsn }}
