version: 1

update_configs:
  - package_manager: "ruby:bundler"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
     - brenetic
     - tomas-stefano
  - package_manager: "docker"
    directory: "/docker/api"
    update_schedule: "daily"
    default_reviewers:
     - brenetic
     - tomas-stefano
  - package_manager: "docker"
    directory: "/docker/worker"
    update_schedule: "daily"
    default_reviewers:
     - brenetic
     - tomas-stefano
